export enum EcomAction{

    SUCCESS='SUCCESS',
    FAIL="FAIL",

    AUTH_TOKEN_NULL='AUTH_TOKEN_NULL',
    AUTH_TOKEN='AUTH_TOKEN',
    

    LOGIN='LOGIN',
    LOGGING_IN='LOGGING_IN',
    LOGGED='LOGGED',
    LOGIN_ERROR='LOGIN_ERROR',

    REGISTER='REGISTER',
    REGISTERING='REGISTERING',
    REGISTERED='REGISTERED',
    REGISTRATION_ERROR='REGISTRATION_ERROR',

    GETUSER='GETUSER',
    GETUSER_LODING='GETUSER_LODING',
    GETUSER_LODED='GETUSER_LODED',
    GETUSER_LODING_ERROR='GETUSER_LODING_ERROR',

    GETCATEGORIES='GETCATEGORIES',
    GETCATEGORIES_LODING='GETCATEGORIES_LODING',
    GETCATEGORIES_LODED='GETCATEGORIES_LODED',
    GETCATEGORIES_LODING_ERROR='GETCATEGORIES_LODING_ERROR',

    GET_BEST_SELLINGS_PHONE='GET_BEST_SELLINGS_PHONE',
    BEST_SELLINGS_LOADING='BEST_SELLINGS_LOADING',
    BEST_SELLINGS_LOADED='BEST_SELLINGS_LOADED',
    BEST_SELLINGS_LOADING_ERROR='BEST_SELLINGS_LOADING_ERROR',

    ADD_TO_CART='ADD_TO_CART',
    ADD_TO_CART_LOADING='ADD_TO_CART_LOADING',
    ADD_TO_CART_LOADED='ADD_TO_CART_LOADED',
    ADD_TO_CART_LOADING_ERROR='ADD_TO_CART_LOADING_ERROR',

    ALREADY_ADD_TO_CART='ALREADY_ADD_TO_CART_LOADING',
    ALREADY_ADD_TO_CART_LOADING='ALREADY_ADD_TO_CART_LOADING',
    ALREADY_ADD_TO_CART_LOADED='ALREADY_ADD_TO_CART_LOADED',
    ALREADY_ADD_TO_CART_LOADING_ERROR='ALREADY_ADD_TO_CART_LOADING_ERROR',


    GET_CART_ITEM='GET_CART_ITEM',
    GET_CART_ITEM_LOADING='GET_CART_ITEM_LOADING',
    GET_CART_ITEM_LOADED='GET_CART_ITEM_LOADED',
    GET_CART_ITEM_LOADING_ERROR='GET_CART_ITEM_LOADING_ERROR',
    UPDATEQTY='UPDATEQTY'


    
}