export enum ChatAction{

    SUCCESS='SUCCESS',
    FAIL="FAIL",
    

    LOGIN='LOGIN',
    LOGGING_IN='LOGGING_IN',
    LOGGED='LOGGED',
    LOGIN_ERROR='LOGIN_ERROR',

    REGISTER='REGISTER',
    REGISTERING='REGISTERING',
    REGISTERED='REGISTERED',
    REGISTRATION_ERROR='REGISTRATION_ERROR'


    

}